### ISSUE TITLE
Manuscript Revision Checklist

### ISSUE THREAD

**Issue by zen-juen** [neuropsychology/NeuroKit#353]
The Neurokit manuscript was sent back for revision albeit with pretty positive and helpful suggestions for changes 😄 @DominiqueMakowski @Tam-Pham  @JanCBrammer @sangfrois @hungpham2511 Putting a checklist here to track our progress before resubmitting!

### 1) NK and other products

- [x] Compare briefly NK vs. competing products E.g., with [MNE-Python](https://mne.tools/stable/index.html) or [OpenVibe](http://openvibe.inria.fr).
   (http://openvibe.inria.fr), state why nk does not serve the same goals, what's the main difference and under what situation nk is best suited and preferred
  - *Dom: For mne-python and OpenVibe, there are not really comparable, as they are respectively for M/EEG and BCI, which nk's support is not developed in the paper. That being said we could talk a bit about other packages/software? kubios, acknowledge, ...*
- [ ] Can also state how nk can be interfaced with other tools like [PsychoPy](https://www.psychopy.org/) or other major packages
  - *Dom: For psychopy, opensesame or [neuropsydia](https://github.com/neuropsychology/Neuropsydia.py), no official interfacing but as the experiments they produce are written in pure python, neurokit functions can easily be inserted in them.*

### 2) Fix **examples**
- [x] Reviewer 1: Invert the examples? Reviewer thinks it's weird to see that the second example is a copy of the first, with one less step. Perhaps it would be more appropriate to see the simpler example first, and then add the epoching step later on
  - *Dom: makes sense*
- [x] Reviewer 2: Inconsistent example results (https://github.com/neuropsychology/NeuroKit/issues/351), examine and address the improved results, provide expected results with the current release version + specify code versions used to run the examples
- [x] Specify structure of `bio_eventrelated_100hz` - single subject? SQL database or panda collection?
- [ ] Figure 1 caption: make it more informative + add link to script used to generate the figure.
  - *Dom: though it's mostly R, but we can mention that "the code to reproduce this figure is available on the software's github"*
- [ ] Specify where [["ECG_Rate_Mean", "HRV_RMSSD", "RSP_Rate_Mean", "RSA_P2T_Mean"]] come from, how do we know they hold the results?
- [x] Have binder link for 2 examples?
  - *Dom: @sangfrois can it be done?*

### 3) Enhance design philosophy description
- [x] Add figure explaining the overall package architecture
- Describing and expanding on **Functionality**
  - [x] What analyses can be applied, not what modalities are supported
  - [x] Additional descriptions of available tooling (examples are useful but largely describe higher level functionality (clean, process, etc), which are somewhat opaque as to what processes are applied to the data) - can talk about nk's functions for simulating data, plotting options
  - [x] Add extra paragraph (page 4) succinctly listing out functionality available

> e.g. "NeuroKit2 provides functionality such data and event management; signal processing including filtering, resampling, ...; spectral analyses such as computing power spectral densities; statistical analyses such as ...; complexity analyses such as ..., plotting such as ...". 

- [ ] If there are more workflows described by prior publications available, such as the 'khodadad2018' method noted later in the paper, some more of these could be mentioned and cited, as examples.

### 4) Noting Programming Requirements & Interface
- [x] Make intro and discussion clearer that nk is used as a Python interface + what level of Python required from users (specifically, that nk *does* require some programming)
  -  Not very clear how nk addresses the challenge of GUIs not being reproducible (we also state that many algorithms are inaccessible to those without programming experience, which may suggest nk has a GUI interface) Slightly later the article notes that GUIs are not very reproducible (which I believe is a fair comment).
  - First line of discussion overstates nk's accessibility to all levels of experience since for users to validate and apply the different pipeline approaches on data requires some knowledge of processing + programming: 

> E.g., "Neurokit2 does require using Python. For the beginner program, the documentation also includes guidance on getting started with Python"

### 5) Enhance Discussion
- Clarify what high-level functions are still missing and the direction in which nk is going to implement these
  - [ ] Explain state of unittest, documentation, development, short-term targets
    - *Zen: since pytest is already mentioned in the body of the paragraph, we can talk about following coding best practices to maintain readability of code, use of black/pylint/docformatter*
  - [ ] State whether there are plans of advertising package (tutorial or spring at conferences), hire dedicated developers through grants - why if not
  - [x] Give stronger arguments about reproducibility and how it can impact research in long run

### 6) Add paragraph on how to install nk
- [x] State if it is available on pip and/or conda
- [x] Does it have a unittest suit and what is the test coverage
- [x] What are the dependencies?
- [x] Clarify if there is any documentation and/or tutorial

## Minor Issues
- [x] Replace "alot of parameters” (line 114) with “several” or “multiple”. 
- [x] Add current active users / collaborators (line 88)
- [x] User interface usually shortened to UI (line 100), refers to the visual aspect of an interface
- [x] Term **user friendly** (line 62): not wise to use this term, replace with term **user-centered which is instead related to the Design Approach used
- [x] Term **professional** (line 71): Avoid using the term unless design guidelines and widely adopted conventions have been used and reported.
- [x] Replace word "upload" with "submitting" (line 83) as former may suggest immediate feedback for newcomers not familiar with github
- [x] Cite other software packages (line 75, page 4): describe citations that can be used for numpy, matplotlib, etc: https://www.scipy.org/citing.html
- [x] Jupyter notebooks not Python notebooks (line 84, page 4)
- [x] Unclear what peer-reviewed processing pipelines mean (line 90, page 5) is it implementations of these pipelines described in peer-reviewed literature or is it a peer-review system that reviews code for processing pipelines?
- [x] Describe and spell out acronyms e.g., `RSP` (line 121, page 6 example) *start looking from page 5 line 64 onwards
- [x] Duplication of word *three* (line 110, page 5)

**Comment by cnboonhan94** [comment]
Nice

**Comment by DominiqueMakowski** [comment]
Maybe we should put each "point" in a separate issue so we can also comment how we addressed said-point. It will be easier to later make the "response to reviewers" file that goes along the resubmission, in which we have to say to each point how exactly we have addressed it, indicate the lines of the change and paste the updated paragraph.

We could also link each issue in that file, so the reviewers can exactly see the commits referencing each of their point and the eventual discussions surrounding them. I mean it might be pushing open science too far but 🤷‍♂️

**Comment by sangfrois** [comment]
These are constructive comments! Good job for putting this together in a comprehensible way. 

@DominiqueMakowski I have a suggestion that could answer to your last comment : would it be appropriate if I open an issue (or a PR?) that aggregates 2), 6). I see my input on binder/examples and on tutorials quite well together. we could also reference the issue (or PR) related to each point in the description here. Would that be suitable ? I'll let you judge and initiate the proper move accordingly.

We have to continue to push for open science, and not fall under pressure (that's my take on the subject 👍 ).

**Comment by DominiqueMakowski** [comment]
@sangfrois yeah do go ahead. though I'd say we can open 2 separate issues for 2 and 6 and link the PR(s) to them accordingly (the same PR can be linked to both) but it will be easier for us to have as specific issues as possible.

Also, I think I'll create an `R1.md` file in /paper/ with our answers to reviewers that we can update alongside our fixes, It'll be easier than doing it at the end ☺️

**Comment by sangfrois** [comment]
All right!! I will start by 2). 

Also : I've put together a google document so we could have a formatted version of original reviewer's comments.

[shared google doc](https://docs.google.com/document/d/1pC18MtedYd-WE_dQ1exjxNorgJWBabgU179HldZEYtM/edit?usp=sharing)

**Comment by zen-juen** [comment]
Hey guys, do check out the individual issues opened for fixing the manuscript 😄

I tried to ensure one commit = one issue fixed so its easier to track the changes!

**Comment by zen-juen** [comment]
@sangfrois Let us know what you think about the commented parts  regarding the examples and then we can go ahead and finalize everything https://docs.google.com/document/d/1pC18MtedYd-WE_dQ1exjxNorgJWBabgU179HldZEYtM/edit 😄

**Comment by JanCBrammer** [comment]
@DominiqueMakowski , @zen-juen, @Tam-Pham, @sangfrois, as discussed, I just pushed my final edits (changed the corresponding sections in the Google doc as well.)

**Comment by DominiqueMakowski** [comment]
perfect, thanks, we'll generate the manuscript and do a final pass tomorrow ☺️
