### ISSUE TITLE
Manuscript Revision Checklist - Fix all Minor Issues + 6) Install NK paragraph

### ISSUE THREAD

**Issue by zen-juen** [neuropsychology/NeuroKit#356]
#  Minor Issues
- [x] Replace "alot of parameters” (line 114) with “several” or “multiple”. 
- [x] Add current active users / collaborators (line 88)
- [x] User interface usually shortened to UI (line 100), refers to the visual aspect of an interface
- [x] Term **user friendly** (line 62): not wise to use this term, replace with term **user-centered which is instead related to the Design Approach used
- [x] Term **professional** (line 71): Avoid using the term unless design guidelines and widely adopted conventions have been used and reported.
- [x] Replace word "upload" with "submitting" (line 83) as former may suggest immediate feedback for newcomers not familiar with github
- [x] Cite other software packages (line 75, page 4): describe citations that can be used for numpy, matplotlib, etc: https://www.scipy.org/citing.html
- [x] Jupyter notebooks not Python notebooks (line 84, page 4)
- [x] Unclear what peer-reviewed processing pipelines mean (line 90, page 5) is it implementations of these pipelines described in peer-reviewed literature or is it a peer-review system that reviews code for processing pipelines?
  - **Zen**: *Not exactly peer reviewed right? More like opened issues and discussed with original authors etc.*
- [x] Describe and spell out acronyms e.g., `RSP` (line 121, page 6 example) *start looking from page 5 line 64 onwards
- [x] Duplication of word *three* (line 110, page 5)

# Add paragraph on how to install nk

Paragraph to be before Examples perhaps?

- [x] State if it is available on pip and/or conda
- [x] Does it have a unittest suit and what is the test coverage
  - **Zen**: *can mention pytest and test coverage (being 83%)*
- [x] What are the dependencies?
  - **Zen**: *Already mentioned in "The package depends on relatively few, well established and robust packages from the Python data analysis ecosystem..."*
- [x] Clarify if there is any documentation and/or tutorial
  - **Zen**: * provided link to readthedocs page for neurokit and python installation
  
See https://github.com/neuropsychology/NeuroKit/issues/353
