### ISSUE TITLE
Manuscript Revision Checklist - 3) Design Philosophy

### ISSUE THREAD

**Issue by zen-juen** [neuropsychology/NeuroKit#357]
### Enhance design philosophy description
- [x] Add figure explaining the overall package architecture
- Describing and expanding on **Functionality**
  - [x] What analyses can be applied, not what modalities are supported
  - [x] Additional descriptions of available tooling (examples are useful but largely describe higher level functionality (clean, process, etc), which are somewhat opaque as to what processes are applied to the data) - can talk about nk's functions for simulating data, plotting options
  - [x] Add extra paragraph (page 4) succinctly listing out functionality available
- [ ] If there are more workflows described by prior publications available, such as the 'khodadad2018' method noted later in the paper, some more of these could be mentioned and cited, as examples.

### What has been done
- Zen: NeuroKit2 offers a breadth of functionalities which includes, but is not limited to: (1) signal simulation, (2) data management (e.g., downloading data from the GitHub repository, reading and formatting files into a dataframe), (3) events extraction from signals, (4) epochs extraction, (5) signal processing (e.g., filtering, resampling, rate computation) (6) spectral analyses such as computing power spectral densities, (7) complexity analyses such as time-delay embedding of time series data, (8) entropy computation, (9) clustering analysis using a variety of different algorithms (e.g., K-means, independent component analysis, principal component analysis) and (10) statistical analysis such as polynomial regressions and kernel density estimations. There is also an extensive host of plotting options, allowing for quick visualization of processed signals (e.g., raw, cleaned, and decomposed signals) as well as visualization of events in a signal. *NeuroKit2* can also perform event-related analysis and resting-state analysis on specific bodily signals (as demonstrated in the *Examples* section of this paper) and EEG microstates segmentation, a functionality currently being expanded and improved on.

See #353
