### ISSUE TITLE
Manuscript Revision Checklist - 1) NK vs other products + 4) Noting Programming Requirements & Interface

### ISSUE THREAD

**Issue by zen-juen** [neuropsychology/NeuroKit#358]
### 1) NK and other products

- [x] Compare briefly NK vs. competing products E.g., with [MNE-Python](https://mne.tools/stable/index.html) or [OpenVibe](http://openvibe.inria.fr).
   (http://openvibe.inria.fr), state why nk does not serve the same goals, what's the main difference and under what situation nk is best suited and preferred
  - *Dom: For mne-python and OpenVibe, there are not really comparable, as they are respectively for M/EEG and BCI, which nk's support is not developed in the paper. That being said we could talk a bit about other packages/software? kubios, acknowledge, ...*
- [ ] Can also state how nk can be interfaced with other tools like [PsychoPy](https://www.psychopy.org/) or other major packages
  - *Dom: For psychopy, opensesame or [neuropsydia](https://github.com/neuropsychology/Neuropsydia.py), no official interfacing but as the experiments they produce are written in pure python, neurokit functions can easily be inserted in them.*

### 4) Noting Programming Requirements & Interface
- [x] Make intro and discussion clearer that nk is used as a Python interface + what level of Python required from users (specifically, that nk *does* require some programming)
  -  Not very clear how nk addresses the challenge of GUIs not being reproducible (we also state that many algorithms are inaccessible to those without programming experience, which may suggest nk has a GUI interface) Slightly later the article notes that GUIs are not very reproducible (which I believe is a fair comment).
      - *Zen: how nk addresses GUI challenges not addressed yet*
  - First line of discussion overstates nk's accessibility to all levels of experience since for users to validate and apply the different pipeline approaches on data requires some knowledge of processing + programming: 
      - *Zen: changed this to "different levels of experience"*

> E.g., "Neurokit2 does require using Python. For the beginner program, the documentation also includes guidance on getting started with Python"

See #353 

I'm combining these two issues as the programming requirements of python would be a key comparison of nk vs other products

### What has been done
- Zen: mentioned this in the discussion (1st para): For users who are novice programmers or are new to the neurophysiology field, the package presents an ideal opportunity for exploration and learning. The experienced programmer on the other hand, is encouraged to choose and validate the preprocessing and analysis pipelines most appropriate for their data, where any suggestions for improvements is open for discussion within the community. 
- Zen: mentioned this in introduction: The target audience of NeuroKit2 includes both experienced and novice programmers, where documentation  on getting started with Python is available for the latter
- Tam: in response to gap: While many of the existing software caters to only one specific signal type 
such as *KUBIOS* [@tarvainen2014kubios], *HeartPy* [@HeartPy] and *pyHRV* [@gomes2019pyhrv] for ECG signal, *cvxEDA* [@greco2015cvxeda], *Ledalab* [@benedek2010continuous], and *SCRalyze* [@bach2014head] for EDA signal, *NeuroKit2* provides support for various signals and allows its users to process multiple types of signals at once, using the high-level meta-functions (more details in the **Design Philosophy**).
