### ISSUE TITLE
Manuscript revision checklist - 2) Fix examples

### ISSUE THREAD

**Issue by sangfrois** [neuropsychology/NeuroKit#360]
## Comments considering the examples

- [x] invert the examples.

- [x] Inconsistent example results (#351), examine and address the improved results, provide expected results with the current release version

- [x]  specify code versions used to run the examples

- [x] Specify structure of datasets

- [ ] Reference the script used to generate figures

- [x] Binder links, etc.

**Comment by sangfrois** [comment]
Inverting examples
sangfrois@0d9955cf

**Comment by sangfrois** [comment]
inserting binder links

sangfrois@2994b936
