### ISSUE TITLE
Manuscript Revision Checklist - 5) Enhance Discussion

### ISSUE THREAD

**Issue by zen-juen** [neuropsychology/NeuroKit#365]
### Enhance Discussion
- Clarify what high-level functions are still missing and the direction in which nk is going to implement these
  - [x] Explain state of unittest, documentation, development, short-term targets
    - Zen: since pytest is already mentioned in the body of the paragraph, we can talk about following coding best practices to maintain readability of code, use of black/pylint/docformatter
  - [ ] State whether there are plans of advertising package (tutorial or spring at conferences), hire dedicated developers through grants - why if not
  - [x] Give stronger arguments about reproducibility and how it can impact research in long run

### What has been done
- *Zen: added paragraph in discussion regarding code quality - NeuroKit2 also prioritizes a high standard of quality control during code development. This is done through automated testing of code using unittest-based tests that follow coding best practices, reducing code complexity and maintaining code readability. Additionally, we provide guidelines for new contributors to follow when writing  code, encouraging them to follow PEP 8 coding conventions and fix code errors, as documented in our `readthedocs` page (*https://neurokit2.readthedocs.io/en/latest/contributing/contributing.html*).*
- *TamZen*: added paragraph in discussion about reproducibility arguments which are two-fold: 1) nk as compared to other black-box softwares allows for better tracing of the discrepancy of results in analysis pipelines, 2) nk offers several methods, allows for comparison and benchmarking of derived results

See #353
