### ISSUE TITLE
Improve automated detection of noisy chunks in ECG

### ISSUE THREAD

**Issue by DominiqueMakowski** [neuropsychology/NeuroKit#846]
Thanks for sharing these thoughts! Your point about using a rolling measure of variance and complexity certainly got me thinking. Interestingly, Kubios HRV does have an automatic artifact correction feature. I'm not sure if it could serve as a foundation, but I'm currently testing it and it seems to work pretty well ([here](https://www.kubios.com/hrv-preprocessing/)). However, I'd prefer not to rely on paid, closed-source software, and would love to transition entirely to a solution like NK2 for this kind of processing.

_Originally posted by @DanDKL in https://github.com/neuropsychology/NeuroKit/discussions/843#discussioncomment-6222137_
```[tasklist]
### Tasks
- [ ] What is Kubios doing?
- [ ] Get a "benchmark" signal example with noisy chunks vs. clean ones where we can test and compare methods
- [ ] How do rolling SD / complexity behave
```
